config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'search' => 'welcome#search', as: 'search'
  get 'save' => 'welcome#save', as: 'save'
  get 'unsave' => 'welcome#unsave', as: 'unsave'
  get 'report' => 'welcome#report', as: 'report'
  get 'unreport' => 'welcome#unreport', as: 'unreport'
  get 'saved' => 'welcome#saved', as: 'saved'
  get 'privacy' => 'welcome#privacy', as: 'privacy'
  get 'contact' => 'welcome#contact', as: 'contact'
  get 'auto' => 'welcome#auto', as: 'auto'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_sarray, only: ["index", "search"]
  
  def index
  end
  
  def search
    require "elasticsearch"
    require 'json'

    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    )

    if params[:q].present?
    query = {}
    query[:bool] = {}
    query[:bool][:must] = []
    query[:bool][:must] << {simple_query_string: {query: params[:q].to_s, fields: ["a^10", "b^5", "c"], default_operator: "and"}}
    else
    query = {}
    query[:bool] = {}
    query[:bool][:must] = []
    query[:bool][:must] << {match_all: {}}
    end

    if ((params[:minp].present?) && (params[:maxp].present?))
      query[:bool][:must] << {range: {m: {gte: params[:minp].to_i, lte: params[:maxp].to_i }}}
    elsif ((params[:minp].present?) && (!params[:maxp].present?))
      query[:bool][:must] << {range: {m: {gte: params[:minp].to_i }}}
    elsif ((!params[:minp].present?) && (params[:maxp].present?))
      query[:bool][:must] << {range: {m: {lte: params[:maxp].to_i }}}
    end
    
    sortarray = ["_score"]
    sortarray << {m: "asc"} if (params[:sort].to_s == "masc")
    sortarray << {m: "desc"} if (params[:sort].to_s == "mdesc")
    sortarray << {y: "desc"} if (params[:sort].to_s == "ydesc")
    sortarray << {e: "desc"} if (params[:sort].to_s == "edesc")
    sort = sortarray.reverse

    from = (params[:page].to_i - 1) * 20
    size = 20
    
    results = searchclient.search(
      index: "p", 
      body: {
        query: query,
        sort: sort,
        from: from,
        size: size 
      }
    )
    
    @total_results = results.to_h['hits']['total']['value']
    @results = results.to_h['hits']['hits']

    # Did you mean: ...?
suggestion = searchclient.search(
  index: "auton",
  body: { 
    "suggest": {
    "text": params[:q].to_s,
    "simple_phrase": {
      "phrase": {
        "field": "title.trigram",
        "size": 1,
        "gram_size": 3,
        "direct_generator": [ {
          "field": "title.trigram",
          "suggest_mode": "always"
        } ],
        "highlight": {
          "pre_tag": "<strong><em>",
          "post_tag": "</em></strong>"
        }
      }
    }
    }
  }
)
@total_suggests = suggestion.to_h['suggest']['simple_phrase'][0]['options']
    
    if (params[:page].present?) && (params[:page].to_i > 25)
      redirect_to root_path
    end

    # render RSS
    if params[:rss].to_s == "true"
  		render "welcome/rss", :layout => false, content_type: "application/xml"
  	end

    unless cookies[:hsh].present?
    # queries cookies
    if params[:q].present?
    cookies.permanent["q#{params[:c]}"] = JSON.generate([]) if cookies["q#{params[:c]}"].blank?
    array = JSON.parse(cookies["q#{params[:c]}"])
    new_array = array << params[:q].to_s.downcase
    new_array = new_array.uniq.last(10)
    cookies.permanent["q#{params[:c]}"] = JSON.generate(new_array)
    end
    end

    @startol = from + 1
    
  end
  
  def save
    #update ES record
    require "elasticsearch"
    require 'json'

    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    )
    cookies.permanent["#{params[:cat]}"] = JSON.generate([]) if cookies["#{params[:cat]}"].blank?
    link = params[:link].to_s
    if (cookies["#{params[:cat]}"].present?) && (JSON.parse(cookies["#{params[:cat]}"]).exclude? link)
      array = JSON.parse(cookies["#{params[:cat]}"])
      new_array = array << link
      if (cookies["#{params[:cat]}"].size.to_i > 3800)
        new_array = new_array.drop(1)
      end
      cookies.permanent["#{params[:cat]}"] = JSON.generate(new_array)
      current = searchclient.get(id: params[:link].to_s, index: "#{params[:cat]}")["_source"]["y"]
      count = current.to_i + 1
      cookies.permanent["stop#{params[:cat]}"] = "true"
      searchclient.update(id: params[:link].to_s, index: "#{params[:cat]}", body: { doc: {"y": count} })
    end
  end
  
  def unsave
    #update ES record
    require "elasticsearch"
    require 'json'

    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    )
    link = params[:link].to_s
    if (cookies["#{params[:cat]}"].present?) && (JSON.parse(cookies["#{params[:cat]}"]).include? link)
      array = JSON.parse(cookies["#{params[:cat]}"])
      new_array = array - [link]
      cookies.permanent["#{params[:cat]}"] = JSON.generate(new_array)
      cookies.delete("#{params[:cat]}") if (new_array.count == 0)
      current = searchclient.get(id: params[:link].to_s, index: "#{params[:cat]}")["_source"]["y"]
      count = current.to_i - 1
      searchclient.update(id: params[:link].to_s, index: "#{params[:cat]}", body: { doc: {"y": count} })
    end
  end
  
  def report
    #update ES record
    require "elasticsearch"
    require 'json'

    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    )
    cookies.permanent[:report] = JSON.generate([]) if cookies[:report].blank?
    link = params[:link].to_s
    if (cookies[:report].present?) && (JSON.parse(cookies[:report]).exclude? link)
      array = JSON.parse(cookies[:report])
      new_array = array << link
      if (cookies[:report].size.to_i > 3800)
        new_array = new_array.drop(1)
      end
      cookies.permanent[:report] = JSON.generate(new_array)
      current = searchclient.get(id: params[:link].to_s, index: "#{params[:cat]}")["_source"]["z"]
      count = current.to_i + 1
      searchclient.update(id: params[:link].to_s, index: "#{params[:cat]}", body: { doc: {"z": count} })
    end

    puts params
    redirect_back(fallback_location: root_path)
  end
  
  def saved
    require "elasticsearch"
    require 'json'
    require 'httparty'

    if cookies["p"].present?
    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    ) 

    results = searchclient.mget(
      index: "p", 
      body: { 
          ids: JSON.parse(cookies["p"])
      }
    )
    
    @total_results_p = results.to_h['docs'].count
    @results_p = results.to_h['docs'].reverse
    else
    @total_results_p = 0
    end

    @all_count = @total_results_p
  end
  
  def privacy
  end

  def auto
    if cookies[:hss].present?
      array = []
    else
    # limit string to 40 characters
    require "elasticsearch"
    require 'json'

    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    )

 results = searchclient.search(
  index: "auton",
  body: { 
    query: { 
      "multi_match": {
      "query": params[:q].to_s,
      "type": "bool_prefix",
      "fields": [
        "terms",
        "terms._2gram",
        "terms._3gram"
      ]
      }
    }, 
  "collapse": {
    "field": "title"         
  },
    "suggest": {
    "text": params[:q].to_s,
    "simple_phrase": {
      "phrase": {
        "field": "title.trigram",
        "size": 1,
        "gram_size": 3,
        "direct_generator": [ {
          "field": "title.trigram",
          "suggest_mode": "always"
        } ]
      }
    }
    },
    size: 8
  }
)
    total_results = results.to_h['hits']['total']['value']
    if total_results.to_i > 0
    allresults = results.to_h['hits']['hits']
    array = allresults.map { |x| x['_source']['terms'] }
    else
      total_suggests = results.to_h['suggest']['simple_phrase'][0]['options']
      if total_suggests.count > 0
      query = total_suggests[0]['text']
results = searchclient.search(
  index: "auton",
  body: { 
    query: { 
      "multi_match": {
      "query": query,
      "type": "bool_prefix",
      "fields": [
        "terms",
        "terms._2gram",
        "terms._3gram"
      ]
      }
    }, 
  "collapse": {
    "field": "title"         
  },
    size: 8
  }
)
    total_results = results.to_h['hits']['total']['value']
    if total_results.to_i > 0
    allresults = results.to_h['hits']['hits']
    array = allresults.map { |x| x['_source']['terms'] }
    else
      array = []
    end
      else
        array = []
      end
    end
    end # end of cookie condition
    render json: array.first(8)
   end

  def set_sarray
    if cookies[:hsh].present?
      @sarray = []
    else
    if ((params[:c].present?) && (["s","r", "j"].include? "#{params[:c]}"))
     if (cookies["q#{params[:c]}"].present?)
      @sarray = JSON.parse(cookies["q#{params[:c]}"]).reverse
     else 
      @sarray = []
     end
    else
     if (cookies["qp"].present?)
      @sarray = JSON.parse(cookies["qp"]).reverse
     else 
      @sarray = []
     end
    end
    end # end of cookie condition

    @psarray = ["fresh eggs", "used cars"]
    
  end

  end

app/views/welcome/index.html.erb
<% content_for :head do %>
  <title>OpenSorted - <%= t 'search-ads' %></title>
<% end %>

<%= render "welcome/shared/search_form" %>
  
<div class="homedesc">
  <%= t 'search-billions' %>
</div>
      
<% if (params[:c].blank?) || (params[:c].to_s == "p") %>
  <% if (cookies["p"].present?) && (JSON.parse(cookies["p"]).count > 0) %>
    <div style="text-align:center;font-size:14px;margin-top:40px">
      <b><%= link_to t('saved'), saved_path, style: "color:#222" %></b> (<%= JSON.parse(cookies["p"]).count %>)
    </div>
  <% end %>
<% elsif (params[:c].present?) || (params[:c].to_s == "s") %>
  <% if (cookies["s"].present?) && (JSON.parse(cookies["s"]).count > 0) %>
    <div style="text-align:center;font-size:14px;margin-top:40px">
      <b><%= link_to t('saved'), saved_path, style: "color:#222" %></b> (<%= JSON.parse(cookies["s"]).count %>)
    </div>
  <% end %>
<% elsif (params[:c].present?) || (params[:c].to_s == "r") %>
  <% if (cookies["r"].present?) && (JSON.parse(cookies["r"]).count > 0) %>
    <div style="text-align:center;font-size:14px;margin-top:40px">
      <b><%= link_to t('saved'), saved_path, style: "color:#222" %></b> (<%= JSON.parse(cookies["r"]).count %>)
    </div>
  <% end %>
<% elsif (params[:c].present?) || (params[:c].to_s == "j") %>
  <% if (cookies["j"].present?) && (JSON.parse(cookies["j"]).count > 0) %>
    <div style="text-align:center;font-size:14px;margin-top:40px">
      <b><%= link_to t('saved'), saved_path, style: "color:#222" %></b> (<%= JSON.parse(cookies["j"]).count %>)
    </div>
  <% end %>
<% end %>
  
<script>
window.addEventListener("load", () => {
  if ("serviceWorker" in navigator) {
    navigator.serviceWorker.register("service-worker.js");
  }
});
</script>

app/views/welcome/privacy.html.erb
<% content_for :head do %>
  <title>OpenSorted - Privacy Policy</title>
<% end %>

<div class="staticwrap">
<h3>Privacy policy</h3><br>
  <ul>
    <li>OpenSorted may link to other websites. 
    We have no control over those websites and cannot accept responsibility or liability for their respective content and privacy policies.</li>
    <li>You do not need to register or share any personal information to use this website.</li>
    <li>Only the information that you type in a search query or the basic information your browser automatically sends is visible to us.</li>
    <li>Various cookies are stored on your browser. They contain information about search settings.</li>
  </ul>
</div>

app/views/welcome/rss.html.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">

<channel>
  <title>OpenSorted</title>
  <link>https://www.opensorted.com</link>
  <description>Search products, services, real estate and jobs</description>
  
  <item>
    <title>title</title>
    <link>https://www.opensorted.com/1</link>
	<pubDate>2000</pubDate>
    <guid>1</guid>
    <description>desc</description>
  </item>
      
</channel>

</rss> 

app/views/welcome/saved.html.erb
<% content_for :head do %>
  <title>OpenSorted - <%= t 'saved' %></title>
<% end %>

<% if @total_results_p > 0 %>
<div class="savedt">
  <%= t 'products' %> (<%= @total_results_p %>)
</div>
  
<%= render "welcome/shared/results", results: @results_p, c: "p" %>
<% end %>

<% if @all_count == 0 %>
  <div class="savedt">
    <%= t 'no-saved' %>
  </div>
<% end %>

app/views/welcome/search.html.erb
<% content_for :head do %>
  <% if params[:q].to_s.present? %>
  <title><%= params[:q].to_s %> - OpenSorted</title>
  <% else %>
  <title>OpenSorted</title>
  <% end %>
<% end %>
  
<%= render "welcome/shared/search_form" %>

<%= render "welcome/shared/results", results: @results, c: params[:c] %>
      
 <div class="hwrap">     
    <div class="ptable-2">
     <% pagination_numbers(params[:page], 20, @total_results).each do |x| %>
        <% if x == "..." %>
          <span data-micromodal-trigger="etcetera" class="etcdots">...</span>
        <% elsif x.to_s == params[:page] %>
          <span><%= link_to x, search_path(params.except(:page).to_enum.to_h.merge(:page => x)), class: "plinka" %></span>
        <% elsif x.to_s == ">" %>
         <span><%= link_to x, search_path(params.except(:page).to_enum.to_h.merge(:page => (params[:page].to_i + 1))), class: "pnext", title: "Next" %></span>
        <% elsif x.to_s == "<" %>
        <span><%= link_to x, search_path(params.except(:page).to_enum.to_h.merge(:page => (params[:page].to_i - 1))), class: "pprev", title: "Previous" %></span>  
        <% else %>
          <span>
            <%= link_to x, search_path(params.except(:page).to_enum.to_h.merge(:page => x)), class: "plink" %>
          <% end %>
          </span>
     <% end %>
    </div>
  </div>

<div style="text-align:center;margin-top:40px;font-size:12px;color:grey">
  <%= link_to t('privacy'), privacy_path, style: 'color:grey' %> •
  <%= link_to t('contact'), privacy_path, style: 'color:grey' %>
</div>

<div class="modal micromodal-slide" id="etcetera" aria-hidden="true">
  <div class="modal__overlay" tabindex="-1" data-micromodal-close>
    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="etcetera-title">
      <div class="pfwrapper" >
      <br>
      <% full_pages(20, @total_results).each do |x| %>
        <%= link_to x, search_path(params.except(:page).to_enum.to_h.merge(:page => x)), class: "pflink" %>
      <% end %>
      <div data-micromodal-close aria-label="Close this dialog window" class="close-modal-text">Close</div>
      <br>
      </div>
    </div>
  </div>
</div>
                  
<div class="modal micromodal-slide" id="sortic" aria-hidden="true">
  <div class="modal__overlay" tabindex="-1" data-micromodal-close>
    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="sortic-title">
      <div>
        <br>
      <div>
        
      <% if params[:sort].blank? %>
       <%= t 'no-sorting' %>
      <% else %>
      <%= link_to t("no-sorting"), search_path(params.except(:sort, :page, :action, :controller).to_enum.to_h.merge(:page => 1)), style: "outline:none" %>
      <% end %>
      </div><br>
      <div>
      <% if params[:sort].to_s == "masc" %>
       <%= t 'lowest-price' %>
      <% else %>
      <%= link_to t("lowest-price"), search_path(params.except(:sort, :page, :action, :controller).to_enum.to_h.merge(:sort => "masc", :page => 1)), style: "outline:none" %>
      <% end %>
      </div><br>
      <div>
      <% if params[:sort].to_s == "mdesc" %>
       <%= t 'highest-price' %>
      <% else %>
      <%= link_to t("highest-price"), search_path(params.except(:sort, :page, :action, :controller).to_enum.to_h.merge(:sort => "mdesc", :page => 1)), style: "outline:none" %>
      <% end %>
      </div><br>
      <div>
      <% if params[:sort].to_s == "edesc" %>
       <%= t 'most-recent' %>
      <% else %>
      <%= link_to t("most-recent"), search_path(params.except(:sort, :page, :action, :controller).to_enum.to_h.merge(:sort => "edesc", :page => 1)), style: "outline:none" %>
      <% end %>
      </div><br>
      <div>
      <% if params[:sort].to_s == "ydesc" %>
       <%= t 'most-popular' %>
      <% else %>
      <%= link_to t("most-popular"), search_path(params.except(:sort, :page, :action, :controller).to_enum.to_h.merge(:sort => "ydesc", :page => 1)), style: "outline:none" %>
      <% end %>
      </div><br>
      <div>
      <% if params[:sort].to_s == "dasc" %>
       <%= t 'nearest-first' %>
      <% else %>
      <%= link_to t("nearest-first"), search_path(params.except(:sort, :page, :action, :controller).to_enum.to_h.merge(:sort => "dasc", :page => 1)), style: "outline:none" %>
      <% end %>
      </div>

      <div data-micromodal-close aria-label="Close this dialog window" class="close-modal-text"><%= t "close" %></div>
      <br>
      </div>
    </div>
  </div>
</div>              

<script>
function srsave(link, cat, url) {
  var element = document.getElementById("save-row-" + link);
  var element2 = document.getElementById("unsave-row-" + link);
  const xhttp = new XMLHttpRequest();
  xhttp.open("GET", "/save?link=" + link + "&cat=" + cat + "&url=" + url);
  xhttp.send();
  setTimeout(function () {
      element.style.display = "none";
      element2.style.display = "inline-block";
  }, 250);
  var name = "cp";
  var match = document.cookie.match(RegExp('(?:^|;\\s*)' + name + '=([^;]*)'));
  if (match) {
    var has_cookie = true;
  } else{
    var has_cookie = null;
  };
  setTimeout(function () {
    if (has_cookie === true){
      alert('You can find saved results in "Products" tab')
      document.cookie = name +"=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;";
    };
  }, 500);
}
</script>