config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'search' => 'welcome#search', as: 'search'
  get 'save' => 'welcome#save', as: 'save'
  get 'unsave' => 'welcome#unsave', as: 'unsave'
  get 'report' => 'welcome#report', as: 'report'
  get 'unreport' => 'welcome#unreport', as: 'unreport'
  get 'saved' => 'welcome#saved', as: 'saved'
  get 'privacy' => 'welcome#privacy', as: 'privacy'
  get 'contact' => 'welcome#contact', as: 'contact'
  get 'auto' => 'welcome#auto', as: 'auto'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_sarray, only: ["index", "search"]
  
  def index
  end
  
  def search
    require "elasticsearch"
    require 'json'

    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    )

    if params[:q].present?
    query = {}
    query[:bool] = {}
    query[:bool][:must] = []
    query[:bool][:must] << {simple_query_string: {query: params[:q].to_s, fields: ["a^10", "b^5", "c"], default_operator: "and"}}
    else
    query = {}
    query[:bool] = {}
    query[:bool][:must] = []
    query[:bool][:must] << {match_all: {}}
    end

    if ((params[:minp].present?) && (params[:maxp].present?))
      query[:bool][:must] << {range: {m: {gte: params[:minp].to_i, lte: params[:maxp].to_i }}}
    elsif ((params[:minp].present?) && (!params[:maxp].present?))
      query[:bool][:must] << {range: {m: {gte: params[:minp].to_i }}}
    elsif ((!params[:minp].present?) && (params[:maxp].present?))
      query[:bool][:must] << {range: {m: {lte: params[:maxp].to_i }}}
    end
    
    sortarray = ["_score"]
    sortarray << {m: "asc"} if (params[:sort].to_s == "masc")
    sortarray << {m: "desc"} if (params[:sort].to_s == "mdesc")
    sortarray << {y: "desc"} if (params[:sort].to_s == "ydesc")
    sortarray << {e: "desc"} if (params[:sort].to_s == "edesc")
    sort = sortarray.reverse

    from = (params[:page].to_i - 1) * 20
    size = 20
    
    results = searchclient.search(
      index: "p", 
      body: {
        query: query,
        sort: sort,
        from: from,
        size: size 
      }
    )
    
    @total_results = results.to_h['hits']['total']['value']
    @results = results.to_h['hits']['hits']

    # Did you mean: ...?
suggestion = searchclient.search(
  index: "auton",
  body: { 
    "suggest": {
    "text": params[:q].to_s,
    "simple_phrase": {
      "phrase": {
        "field": "title.trigram",
        "size": 1,
        "gram_size": 3,
        "direct_generator": [ {
          "field": "title.trigram",
          "suggest_mode": "always"
        } ],
        "highlight": {
          "pre_tag": "<strong><em>",
          "post_tag": "</em></strong>"
        }
      }
    }
    }
  }
)
@total_suggests = suggestion.to_h['suggest']['simple_phrase'][0]['options']
    
    if (params[:page].present?) && (params[:page].to_i > 25)
      redirect_to root_path
    end

    # render RSS
    if params[:rss].to_s == "true"
  		render "welcome/rss", :layout => false, content_type: "application/xml"
  	end

    unless cookies[:hsh].present?
    # queries cookies
    if params[:q].present?
    cookies.permanent["q#{params[:c]}"] = JSON.generate([]) if cookies["q#{params[:c]}"].blank?
    array = JSON.parse(cookies["q#{params[:c]}"])
    new_array = array << params[:q].to_s.downcase
    new_array = new_array.uniq.last(10)
    cookies.permanent["q#{params[:c]}"] = JSON.generate(new_array)
    end
    end

    @startol = from + 1
    
  end
  
  def save
    #update ES record
    require "elasticsearch"
    require 'json'

    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    )
    cookies.permanent["#{params[:cat]}"] = JSON.generate([]) if cookies["#{params[:cat]}"].blank?
    link = params[:link].to_s
    if (cookies["#{params[:cat]}"].present?) && (JSON.parse(cookies["#{params[:cat]}"]).exclude? link)
      array = JSON.parse(cookies["#{params[:cat]}"])
      new_array = array << link
      if (cookies["#{params[:cat]}"].size.to_i > 3800)
        new_array = new_array.drop(1)
      end
      cookies.permanent["#{params[:cat]}"] = JSON.generate(new_array)
      current = searchclient.get(id: params[:link].to_s, index: "#{params[:cat]}")["_source"]["y"]
      count = current.to_i + 1
      cookies.permanent["stop#{params[:cat]}"] = "true"
      searchclient.update(id: params[:link].to_s, index: "#{params[:cat]}", body: { doc: {"y": count} })
    end
  end
  
  def unsave
    #update ES record
    require "elasticsearch"
    require 'json'

    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    )
    link = params[:link].to_s
    if (cookies["#{params[:cat]}"].present?) && (JSON.parse(cookies["#{params[:cat]}"]).include? link)
      array = JSON.parse(cookies["#{params[:cat]}"])
      new_array = array - [link]
      cookies.permanent["#{params[:cat]}"] = JSON.generate(new_array)
      cookies.delete("#{params[:cat]}") if (new_array.count == 0)
      current = searchclient.get(id: params[:link].to_s, index: "#{params[:cat]}")["_source"]["y"]
      count = current.to_i - 1
      searchclient.update(id: params[:link].to_s, index: "#{params[:cat]}", body: { doc: {"y": count} })
    end
  end
  
  def report
    #update ES record
    require "elasticsearch"
    require 'json'

    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    )
    cookies.permanent[:report] = JSON.generate([]) if cookies[:report].blank?
    link = params[:link].to_s
    if (cookies[:report].present?) && (JSON.parse(cookies[:report]).exclude? link)
      array = JSON.parse(cookies[:report])
      new_array = array << link
      if (cookies[:report].size.to_i > 3800)
        new_array = new_array.drop(1)
      end
      cookies.permanent[:report] = JSON.generate(new_array)
      current = searchclient.get(id: params[:link].to_s, index: "#{params[:cat]}")["_source"]["z"]
      count = current.to_i + 1
      searchclient.update(id: params[:link].to_s, index: "#{params[:cat]}", body: { doc: {"z": count} })
    end

    puts params
    redirect_back(fallback_location: root_path)
  end
  
  def saved
    require "elasticsearch"
    require 'json'
    require 'httparty'

    if cookies["p"].present?
    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    ) 

    results = searchclient.mget(
      index: "p", 
      body: { 
          ids: JSON.parse(cookies["p"])
      }
    )
    
    @total_results_p = results.to_h['docs'].count
    @results_p = results.to_h['docs'].reverse
    else
    @total_results_p = 0
    end

    @all_count = @total_results_p
  end
  
  def privacy
  end

  def auto
    if cookies[:hss].present?
      array = []
    else
    # limit string to 40 characters
    require "elasticsearch"
    require 'json'

    searchclient = Elasticsearch::Client.new(
      url: "https://2x4tp7rec4:p6s6rovw46@list-6840506533.us-east-1.bonsaisearch.net:443",
      retry_on_failure: 5,
      request_timeout: 30,
      log: false
    )

 results = searchclient.search(
  index: "auton",
  body: { 
    query: { 
      "multi_match": {
      "query": params[:q].to_s,
      "type": "bool_prefix",
      "fields": [
        "terms",
        "terms._2gram",
        "terms._3gram"
      ]
      }
    }, 
  "collapse": {
    "field": "title"         
  },
    "suggest": {
    "text": params[:q].to_s,
    "simple_phrase": {
      "phrase": {
        "field": "title.trigram",
        "size": 1,
        "gram_size": 3,
        "direct_generator": [ {
          "field": "title.trigram",
          "suggest_mode": "always"
        } ]
      }
    }
    },
    size: 8
  }
)
    total_results = results.to_h['hits']['total']['value']
    if total_results.to_i > 0
    allresults = results.to_h['hits']['hits']
    array = allresults.map { |x| x['_source']['terms'] }
    else
      total_suggests = results.to_h['suggest']['simple_phrase'][0]['options']
      if total_suggests.count > 0
      query = total_suggests[0]['text']
results = searchclient.search(
  index: "auton",
  body: { 
    query: { 
      "multi_match": {
      "query": query,
      "type": "bool_prefix",
      "fields": [
        "terms",
        "terms._2gram",
        "terms._3gram"
      ]
      }
    }, 
  "collapse": {
    "field": "title"         
  },
    size: 8
  }
)
    total_results = results.to_h['hits']['total']['value']
    if total_results.to_i > 0
    allresults = results.to_h['hits']['hits']
    array = allresults.map { |x| x['_source']['terms'] }
    else
      array = []
    end
      else
        array = []
      end
    end
    end # end of cookie condition
    render json: array.first(8)
   end

  def set_sarray
    if cookies[:hsh].present?
      @sarray = []
    else
    if ((params[:c].present?) && (["s","r", "j"].include? "#{params[:c]}"))
     if (cookies["q#{params[:c]}"].present?)
      @sarray = JSON.parse(cookies["q#{params[:c]}"]).reverse
     else 
      @sarray = []
     end
    else
     if (cookies["qp"].present?)
      @sarray = JSON.parse(cookies["qp"]).reverse
     else 
      @sarray = []
     end
    end
    end # end of cookie condition

    @psarray = ["fresh eggs", "used cars"]
    
  end

  end

app/views/welcome/shared/_params.html.erb
<% if (params[:country_code].present?) %>
  <%= hidden_field_tag(:country_code, params[:country_code]) %>
<% end %>
<% if (params[:language_code].present?) %>
  <%= hidden_field_tag(:language_code, params[:language_code]) %>
<% end %>
  
<%= hidden_field_tag :locale, I18n.locale.to_s %>

<% if (["s", "r", "j"].include? "#{params[:c]}") %>
  <%= hidden_field_tag(:c, params[:c], id: "tabf") %>
<% else %>
  <%= hidden_field_tag(:c, "p", id: "tabf") %>
<% end %>

<% if params[:sf].blank? %>
  <%= hidden_field_tag(:sf, "any") %>
<% else %>
  <%= hidden_field_tag(:sf, params[:sf]) %>
<% end %>

<% if params[:lu].blank? %>
  <%= hidden_field_tag(:lu, "") %>
<% else %>
  <%= hidden_field_tag(:lu, params[:lu]) %>
<% end %>

<% if params[:cond].blank? %>
  <%= hidden_field_tag(:cond, "") %>
<% else %>
  <%= hidden_field_tag(:cond, params[:cond]) %>
<% end %>
  
  <%= hidden_field_tag(:page, 1) %>

<% if params[:sort].blank? %>
  <%= hidden_field_tag(:sort, "") %>
<% else %>
  <%= hidden_field_tag(:sort, params[:sort]) %>
<% end %>

<% if params[:rpp].blank? %>
  <% if cookies[:rpp].blank? %>
    <%= hidden_field_tag(:rpp, 10) %>
  <% else %>
    <%= hidden_field_tag(:rpp, cookies[:rpp]) %>
  <% end %>
<% else %>
  <%= hidden_field_tag(:rpp, params[:rpp]) %>
<% end %>  
  
<%= hidden_field_tag(:t, cookies[:t]) %>

app/views/welcome/shared/_results.html.erb
<ol class="olist" start="<%= @startol %>">
<% results.each do |ad| %>
      
      <div class="hwrap">
        <div class="res" id='res-row-<%= ad["_id"] %>'>
            <table cellspacing="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td class="res-td2">
                        <div class="tags">
                          <div style="font-size:18px">   
                            <li>
                             <%= link_to ad["_source"]["a"], root_path %>
                            </li>
                          </div>
                          <div style="font-size:13px;margin-top:3px">
                            <%= ad["_source"]["b"] %> • <%= ad["_source"]["b"] %> • <%= ad["_source"]["b"] %>
                          </div>
                          <div style="font-size:14px;margin-top:4px">
                            <a href='https://<%= ad["_source"]["g"] %>'><%= ad["_source"]["h"] %></a>
                            • <%= ad["_source"]["j"] %>, USA
                          </div>
                          <div class="pricem">
                            <%= ad["_source"]["m"] %> 
                            <%= ad["_source"]["l"].upcase %>
                          </div>
                      </div>
                    <div class="res-date">
                      4 months ago
                    </div>
                    </td>
                    <% unless cookies[:noimg].present? %>
                    <td onclick='setimg("<%= ad["_source"]["d"] %>", "")' class="res-td1">
                      <img lazy='<%= ad["_source"]["d"] %>' src="" data-micromodal-trigger="imgpop" class="res-img" />       
                    </td>
                    <% end %>
                  </tr>
                </tbody>
            </table>
            <div class="res-links">
                      <% ad["_source"]["o"].split(", ").each do |x| %>
                        <%= link_to x.split("#").first.to_s, "#{x.split("#").second.to_s}" %>
                      <% unless x == ad["_source"]["o"].split(", ").last %>
                          • 
                      <% end %>
                      <% end %>
                        • <%= link_to t('directions'), map_provider(cookies[:mapp], ad["_source"]["j"].to_s, "0,0") %> 
                       • 
                      <% if (cookies["#{c}"].present?) && (JSON.parse(cookies["#{c}"]).include? "#{ad["_id"]}") %>
                      <span class="sr sra" id='unsave-row-<%= ad["_id"] %>' onclick='srunsave("<%= ad["_id"] %>", "<%= c %>" , "<%= request.original_url %>")'>
                        <%= t 'saved' %>
                      </span>
                      <span style="display:none" class="sr" id='save-row-<%= ad["_id"] %>' onclick='srsave("<%= ad["_id"] %>", "<%= c %>" , "<%= request.original_url %>")'>
                        <%= t 'save' %>
                      </span>
                      <% else %>
                      <span class="sr" id='save-row-<%= ad["_id"] %>' onclick='srsave("<%= ad["_id"] %>", "<%= c %>" , "<%= request.original_url %>")'>
                        <%= t 'save' %></span>
                      <span style="display:none" class="sr sra" id='unsave-row-<%= ad["_id"] %>' onclick='srunsave("<%= ad["_id"] %>", "<%= c %>" , "<%= request.original_url %>")'><%= t 'saved' %>
                      </span>
                      <% end %>
                       • 
                      <span class="sr" data-micromodal-trigger='report-<%= ad["_id"] %>'>
                        <%= t 'report' %>
                      </span>    

                 <div class="modal micromodal-slide" id='report-<%= ad["_id"] %>' aria-hidden="true">
                  <div class="modal__overlay" tabindex="-1" data-micromodal-close>
                    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="reportpop-title">
                      <%= form_tag(report_path, method: :get) do %>
                      <%= hidden_field_tag :link, ad["_id"] %>
                      <%= hidden_field_tag :url, request.original_url %>
                      <%= hidden_field_tag :cat, params[:c] %>
                      <div class="modal-row">
                      <select name="rtype">
                        <option value="1"><%= t "wrong-info" %></option>
                        <option value="2"><%= t "expired-link" %></option>
                        <option value="3"><%= t "scam" %></option>
                        <option value="4"><%= t "illegal" %></option>
                        <option value="5"><%= t "duplicate" %></option>
                        <option value="6"><%= t "other" %></option>
                      </select>
                      </div>
                      <div class="modal-row">
                        <%= text_area_tag :text, "", placeholder: t("description") %>
                      </div>
                        <div class="modal-buttons">
                          <button><%= t 'save' %></button>
                          <span data-micromodal-close aria-label="Close this dialog window"><%= t 'cancel' %></span>
                        </div>
                      <br>
                      <% end %>
                    </div>
                  </div>
                </div>  
          
            </div>     
        </div>
      </div>               
  <% end %>
</ol>
    
 <div class="modal micromodal-slide" id="imgpop" aria-hidden="true">
  <div class="modal__overlay" tabindex="-1" data-micromodal-close>
    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="imgpop-title">
      <div>
      <br>
      <img src="" id="fullimgx"/>
      <div data-micromodal-close aria-label="Close this dialog window" class="close-modal-text">Close</div>
      <br>
      </div>
    </div>
  </div>
</div>  
            
<script>
loadimages()
</script>   
    

app/views/welcome/shared/_search_form.html.erb
<div class="dropdown">

<%= form_tag(search_path, method: :get, :id => "sform") do %>

<%= render "welcome/shared/params" %>
        
<div class="hwrap">
<div class="sbox">
<div class="forms">
  
  <% if (params[:c].to_s == "p") || (params[:c].nil?) || (["s", "r", "j"].exclude? "#{params[:c].to_s}") %>
    <div class="form show">
      <%= render "welcome/forms/products" %>
    </div>
  <% end %>

  <% if params[:c].to_s == "s" %>
    <div class="form show">
      <%= render "welcome/forms/services" %>
    </div>
  <% end %>

  <% if params[:c].to_s == "r" %>
    <div class="form show">
      <%= render "welcome/forms/estates" %>
    </div>
  <% end %>

  <% if params[:c].to_s == "j" %>
    <div class="form show">
      <%= render "welcome/forms/jobs" %>
    </div>
  <% end %>
  
</div>
</div>
</div>
    
<% end %>
</div>
    
  <% if current_page?(controller: 'welcome', action: 'search') %>
  <div class="hwrap">
    <div class="rcswrapper">
      <div class="sbox">
    <table class="rtable" cellspacing="0" cellpadding="0">
        <tbody>
          <tr>
            <td class="rtable-1">
              <% if @total_results.to_i > 20 %>
                <%= ((params[:page].to_i - 1) * 20) + 1 %>-<%= [(params[:page].to_i * 20), @total_results.to_i].min %>
                 <%= t 'of' %>
              <% end %>
              <b><%= @total_results %></b> <%= t 'results' %>
            </td>
            <td class="rtable-2">
              <% if @total_results.to_i > 0 %>
              <span data-micromodal-trigger="sortic" class="sorti">
                <% if params[:sort].blank? %>
                 <%= t 'sort' %>
                <% elsif params[:sort].to_s == "masc" %>
                 <%= t 'lowest-price' %>
                <% elsif params[:sort].to_s == "mdesc" %>
                 <%= t 'highest-price' %>
                <% elsif params[:sort].to_s == "edesc" %>
                 <%= t 'most-recent' %>
                <% elsif params[:sort].to_s == "ydesc" %>
                 <%= t 'most-popular' %>
                <% elsif params[:sort].to_s == "dasc" %>
                 <%= t 'nearest-first' %>
                <% else %>
                 <%= t 'sort' %>
                <% end %>
              </span>
              <% end %>
            </td>
          </tr>
        </tbody>
    </table>
    </div>
    </div>
  </div>
  <div class="border"></div>
  <% end %>

<% if (current_page?(controller: 'welcome', action: 'search')) && (@total_suggests.count > 0) %>
<div class="hwrap">
  <br>
<div class="sbox">
<%= t 'did-you-mean' %>: <%= link_to @total_suggests[0]["highlighted"].html_safe, search_path(params.except(:q, :action, :controller).to_enum.to_h.merge(:q => @total_suggests[0]["text"])) %> ?
</div>
  <br>
</div>
<% end %>

<script>
function autoc() {
  var field = document.getElementById("qdform");
  
  if (field.value == '') {
 document.getElementById("acomd").style.display = "block";
 const results = document.querySelector("#results");
    results.innerHTML = "";
    var myStringArray = <%= raw @sarray %> ;
    var arrayLength = myStringArray.length;
    if (arrayLength > 0) {
      for (var i = 0; i < arrayLength; i++) {
        row = '<div class="ac-row-wr vqueries" ' + 'onclick=' + '"' + "acset('" + myStringArray[i] + "', '" + 'qdform' + "'" + ')"' + '>' + myStringArray[i] + '</div>'
        results.insertAdjacentHTML("beforeend", row);
      };
    } else {
      var pmyStringArray = <%= raw @psarray %> ;
      var parrayLength = pmyStringArray.length;
      for (var i = 0; i < parrayLength; i++) {
        row = '<div class="ac-row-wr pqueries" ' + 'onclick=' + '"' + "acset('" + pmyStringArray[i] + "', '" + 'qdform' + "'" + ')"' + '>' + pmyStringArray[i] + '</div>'
        results.insertAdjacentHTML("beforeend", row);
      };
    };
  } else{
    document.getElementById("acomd").style.display = "block";
fetch("/auto?q=" + field.value)
  .then((data) => data.text())
  .then((html) => {
    const results = document.querySelector("#results");
    results.innerHTML = "";
    var myStringArray = JSON.parse(html);
    var inputArray = field.value.toLowerCase().split(" ");
    var arrayLength = myStringArray.length;
    for (var i = 0; i < arrayLength; i++) {
      arr = myStringArray[i].split(" ");
      newarr = arr.map(function(i) {
        if (inputArray.includes(i)){
          return i
        }else{
          return '<b>' + i + '</b>'
        }
      }).join(" ");
    row = '<div class="ac-row-wr" ' + 'onclick=' + '"' + "acset('" + myStringArray[i] + "', '" + 'qdform' + "'" + ')"' + '>' + newarr + '</div>'
    results.insertAdjacentHTML("beforeend", row);
    };   
  });
  }
}

</script>